# Generated by Django 5.2.10 on 2026-02-15 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymous_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Client-generated UUID persisted in localStorage",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Django User.id, set when authenticated",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("referrer", models.URLField(blank=True, max_length=2048)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "device_type",
                    models.CharField(
                        blank=True, help_text="desktop | mobile | tablet", max_length=10
                    ),
                ),
            ],
            options={
                "db_table": "analytics_sessions",
                "indexes": [
                    models.Index(
                        fields=["anonymous_id", "-started_at"],
                        name="analytics_s_anonymo_5c7011_idx",
                    ),
                    models.Index(
                        fields=["user_id", "-started_at"],
                        name="analytics_s_user_id_a780aa_idx",
                    ),
                    models.Index(
                        fields=["-started_at"], name="analytics_s_started_ddde48_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdentityLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("anonymous_id", models.UUIDField(db_index=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_identity_links",
                "unique_together": {("anonymous_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="PageViewRollup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("hour", models.DateTimeField(help_text="Truncated to the hour")),
                ("page_path", models.CharField(max_length=2048)),
                ("page_type", models.CharField(blank=True, max_length=30)),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary key of the viewed entity, if applicable",
                        max_length=100,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("unique_sessions", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_pageview_rollups",
                "indexes": [
                    models.Index(
                        fields=["page_type", "-hour"],
                        name="analytics_p_page_ty_63627c_idx",
                    ),
                    models.Index(
                        fields=["entity_id", "-hour"],
                        name="analytics_p_entity__31fe95_idx",
                    ),
                    models.Index(fields=["-hour"], name="analytics_p_hour_d55436_idx"),
                ],
                "unique_together": {("hour", "page_path")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "anonymous_id",
                    models.UUIDField(
                        help_text="Denormalized from session for direct queries"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Django User.id, set when authenticated",
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pageview", "Page View"),
                            ("click", "Click"),
                            ("search", "Search"),
                            ("filter_change", "Filter Change"),
                            ("bill_view", "Bill View"),
                            ("member_view", "Member View"),
                            ("vote_view", "Vote View"),
                            ("share", "Share"),
                            ("signup", "Sign Up"),
                            ("login", "Login"),
                            ("chat_open", "Chat Open"),
                            ("follow", "Follow Member"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Client-reported event time (ISO 8601)"
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        help_text="URL path, e.g. /legislation/hr1234-119",
                        max_length=2048,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        blank=True,
                        help_text="bill | vote | member | chamber | committee | calendar | home",
                        max_length=30,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific data: button_id, search_query, entity_id, etc.",
                    ),
                ),
                ("referrer", models.URLField(blank=True, max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.analyticssession",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="analytics_e_timesta_69b70e_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="analytics_e_event_t_b8bbda_idx",
                    ),
                    models.Index(
                        fields=["page_type", "-timestamp"],
                        name="analytics_e_page_ty_833a9c_idx",
                    ),
                    models.Index(
                        fields=["anonymous_id", "-timestamp"],
                        name="analytics_e_anonymo_f05666_idx",
                    ),
                    models.Index(
                        fields=["user_id", "-timestamp"],
                        name="analytics_e_user_id_376e64_idx",
                    ),
                    models.Index(
                        fields=["session_id", "-timestamp"],
                        name="analytics_e_session_50bdd0_idx",
                    ),
                    models.Index(
                        fields=["event_type", "page_path", "-timestamp"],
                        name="event_path_time_idx",
                    ),
                ],
            },
        ),
    ]
