# Generated by Django 5.2.10 on 2026-01-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=500)),
                ("template_name", models.CharField(max_length=100)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="sent", max_length=20)),
            ],
            options={
                "db_table": "email_logs",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("vote", "New Vote"),
                            ("bill_update", "Bill Update"),
                            ("weekly_recap", "Weekly Recap"),
                            ("weekly_forecast", "Weekly Forecast"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
            },
        ),
    ]
