import Link from "next/link";
import { ChevronLeftIcon, ChevronRightIcon } from "lucide-react";

import {
  getCurrentWeeklySummaries,
  getWeeklySummaryByWeek,
} from "@/lib/api";
import { ChatContextProvider } from "@/lib/chat-context";
import { routes } from "@/lib/routes";
import {
  formatDateLong,
  formatDateParam,
  getDateFromISOWeek,
  getISOWeekNumber,
  parseWeekParam,
} from "@/lib/utils";
import type { WeeklySummary } from "@/types";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import WeekPicker from "@/components/this-week/WeekPicker";

export const revalidate = 900; // 15 minutes

// Earliest allowed week: Jan 2026 (ISO week 1)
const MIN_YEAR = 2026;
const MIN_WEEK = 1;

interface PageProps {
  searchParams: Promise<{ week?: string }>;
}

// Helper: get Monday–Sunday range from ISO week
function isoWeekRange(year: number, week: number) {
  const monday = getDateFromISOWeek(year, week);
  monday.setHours(0, 0, 0, 0);
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);
  return { start: monday, end: sunday };
}

export async function generateMetadata({ searchParams }: PageProps) {
  const params = await searchParams;
  if (params.week) {
    const weekDate = parseWeekParam(params.week);
    const { year, week } = getISOWeekNumber(weekDate);
    const { start, end } = isoWeekRange(year, week);
    const fmt = (d: Date) =>
      d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
    return {
      title: `This Week in Congress — ${fmt(start)} – ${fmt(end)}, ${start.getFullYear()}`,
    };
  }
  return {
    title: "This Week in Congress",
    description:
      "Weekly recap and preview of congressional activity, bills, and votes",
  };
}

function AiDisclaimer() {
  return (
    <p className="text-xs italic text-muted-foreground">
      This summary was generated by AI and provides a nonpartisan overview of
      congressional activity. It may contain inaccuracies.
    </p>
  );
}

function SummaryArticle({ summary }: { summary: WeeklySummary }) {
  const isRecap = summary.summary_type === "recap";

  // Strip markdown bold title line and render paragraphs
  const paragraphs = summary.content
    .replace(/\*\*[^*]+\*\*\s*/g, "") // remove **bold** title blocks
    .replace(/#{1,6}\s+/g, "") // remove markdown headers
    .trim()
    .split(/\n\n+/)
    .filter((p) => p.trim());

  return (
    <article>
      {/* Section label */}
      <p className="mb-2 text-sm font-semibold uppercase tracking-widest text-accent">
        {isRecap ? "Week in Review" : "Week Ahead"}
      </p>

      {/* Headline */}
      <h2 className="mb-2 font-domine text-2xl font-bold text-foreground sm:text-3xl">
        {summary.summary_type_display}
      </h2>

      {/* Meta line */}
      <p className="mb-6 text-sm text-muted-foreground">
        Week {summary.week_number}, {summary.year}
        {summary.votes_included.length > 0 && (
          <> · {summary.votes_included.length} votes</>
        )}
        {summary.bills_included.length > 0 && (
          <> · {summary.bills_included.length} bills</>
        )}
      </p>

      {/* AI disclaimer — top */}
      <div className="mb-6 border-l-2 border-muted-foreground/30 pl-4">
        <AiDisclaimer />
      </div>

      {/* Body paragraphs */}
      <div className="space-y-6">
        {paragraphs.map((paragraph, i) => (
          <p
            key={i}
            className="font-domine font-medium text-xl leading-relaxed text-foreground/85"
          >
            {paragraph.replace(/\*([^*]+)\*/g, "$1").trim()}
          </p>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-8 border-t border-border pt-4">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <time dateTime={summary.created_at}>
            Last updated {formatDateLong(summary.created_at.split("T")[0])}
          </time>
          <Link
            href={routes.calendar.index}
            className="cursor-pointer font-medium text-accent hover:underline"
          >
            View Full Calendar →
          </Link>
        </div>
        {/* AI disclaimer — bottom */}
        <div className="mt-4">
          <AiDisclaimer />
        </div>
      </div>
    </article>
  );
}

function EmptyState() {
  return (
    <div className="py-16 text-center">
      <h2 className="mb-2 text-lg font-medium text-foreground">
        No Summaries Yet
      </h2>
      <p className="text-muted-foreground">
        Weekly summaries are generated automatically. Check back on Saturday for
        the weekly recap and Sunday for the week ahead preview.
      </p>
    </div>
  );
}

export default async function ThisWeekPage({ searchParams }: PageProps) {
  const params = await searchParams;

  // Determine which week to show
  let summaries: WeeklySummary[];
  let isoYear: number;
  let isoWeek: number;

  if (params.week) {
    const weekDate = parseWeekParam(params.week);
    ({ year: isoYear, week: isoWeek } = getISOWeekNumber(weekDate));
    summaries = await getWeeklySummaryByWeek(isoYear, isoWeek);
  } else {
    summaries = await getCurrentWeeklySummaries();
    const summary =
      summaries.find((s) => s.summary_type === "recap") ||
      summaries.find((s) => s.summary_type === "preview");
    if (summary) {
      isoYear = summary.year;
      isoWeek = summary.week_number;
    } else {
      ({ year: isoYear, week: isoWeek } = getISOWeekNumber(new Date()));
    }
  }

  const { start: weekStart, end: weekEnd } = isoWeekRange(isoYear, isoWeek);

  const recap = summaries.find((s) => s.summary_type === "recap");
  const preview = summaries.find((s) => s.summary_type === "preview");
  const currentWeek = recap?.week_number || preview?.week_number;
  const currentYear = recap?.year || preview?.year;

  // Navigation: prev/next week (Monday-based)
  const prevMonday = new Date(weekStart);
  prevMonday.setDate(prevMonday.getDate() - 7);
  const nextMonday = new Date(weekStart);
  nextMonday.setDate(nextMonday.getDate() + 7);

  // Bounds
  const minMonday = getDateFromISOWeek(MIN_YEAR, MIN_WEEK);
  const now = new Date();
  const { year: nowYear, week: nowWeek } = getISOWeekNumber(now);
  const currentActualMonday = getDateFromISOWeek(nowYear, nowWeek);

  const canGoPrev = prevMonday >= minMonday;
  const canGoNext = nextMonday <= currentActualMonday;
  const isCurrentWeek = isoYear === nowYear && isoWeek === nowWeek;

  // Format date range for display
  const formatRange = (start: Date, end: Date) => {
    const startStr = start.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
    });
    const endStr = end.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
    return `${startStr} – ${endStr}`;
  };

  return (
    <ChatContextProvider
      context={{
        type: "this-week",
        data: {
          summary: recap?.content?.slice(0, 500) || "",
          week_number: currentWeek,
          year: currentYear,
        },
      }}
    >
      <main className="min-h-screen bg-background">
        {/* Narrow centered column — NYT article style */}
        <div className="mx-auto max-w-2xl px-4 py-8 sm:px-6">
          {/* Page header */}
          <header className="mb-8">
            <p className="mb-1 text-sm uppercase tracking-widest text-muted-foreground">
              OpenCongress
            </p>
            <h1 className="font-domine text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
              This Week in Congress
            </h1>

            {/* Week navigation */}
            <div className="mt-4 flex flex-wrap items-center gap-3">
              {/* Prev chevron */}
              {canGoPrev ? (
                <Button variant="ghost" size="icon" className="size-8 cursor-pointer" asChild>
                  <Link href={routes.thisWeek.week(formatDateParam(prevMonday))}>
                    <ChevronLeftIcon className="size-5" />
                  </Link>
                </Button>
              ) : (
                <Button variant="ghost" size="icon" className="size-8 opacity-30" disabled>
                  <ChevronLeftIcon className="size-5" />
                </Button>
              )}

              {/* Date range */}
              <span className="text-lg font-medium text-foreground">
                {formatRange(weekStart, weekEnd)}
              </span>

              {/* Next chevron */}
              {canGoNext ? (
                <Button variant="ghost" size="icon" className="size-8 cursor-pointer" asChild>
                  <Link href={routes.thisWeek.week(formatDateParam(nextMonday))}>
                    <ChevronRightIcon className="size-5" />
                  </Link>
                </Button>
              ) : (
                <Button variant="ghost" size="icon" className="size-8 opacity-30" disabled>
                  <ChevronRightIcon className="size-5" />
                </Button>
              )}

              {/* Spacer */}
              <div className="flex-1" />

              {/* Date picker */}
              <WeekPicker
                currentWeekDate={formatDateParam(weekStart)}
                minDate={formatDateParam(minMonday)}
                maxDate={formatDateParam(now)}
              />

              {/* Current Week button */}
              {!isCurrentWeek && (
                <Button variant="outline" size="sm" className="cursor-pointer" asChild>
                  <Link href={routes.thisWeek.index}>Current Week</Link>
                </Button>
              )}
            </div>
          </header>

          <Separator className="mb-8" />

          {/* Articles */}
          {summaries.length === 0 ? (
            <EmptyState />
          ) : (
            <div className="space-y-12">
              {recap && <SummaryArticle summary={recap} />}
              {recap && preview && <Separator />}
              {preview && <SummaryArticle summary={preview} />}
            </div>
          )}

          {/* Bottom nav */}
          <nav className="mt-12 border-t border-border pt-6">
            <div className="flex items-center justify-between text-sm">
              <Link
                href={routes.home}
                className="cursor-pointer font-medium text-foreground hover:text-accent"
              >
                ← Back to Home
              </Link>
              <Link
                href={routes.calendar.index}
                className="cursor-pointer font-medium text-foreground hover:text-accent"
              >
                Full Calendar →
              </Link>
            </div>
          </nav>
        </div>
      </main>
    </ChatContextProvider>
  );
}
