import Link from "next/link";

import { getCurrentWeeklySummaries } from "@/lib/api";
import { ChatContextProvider } from "@/lib/chat-context";
import { routes } from "@/lib/routes";
import { formatDateLong } from "@/lib/utils";
import type { WeeklySummary } from "@/types";
import { Separator } from "@/components/ui/separator";

export const revalidate = 900; // 15 minutes

export const metadata = {
  title: "This Week in Congress",
  description:
    "Weekly recap and preview of congressional activity, bills, and votes",
};

function AiDisclaimer() {
  return (
    <p className="text-xs text-muted-foreground italic">
      This summary was generated by AI and provides a nonpartisan overview of
      congressional activity. It may contain inaccuracies.
    </p>
  );
}

function SummaryArticle({ summary }: { summary: WeeklySummary }) {
  const isRecap = summary.summary_type === "recap";

  // Strip markdown bold title line and render paragraphs
  const paragraphs = summary.content
    .replace(/\*\*[^*]+\*\*\s*/g, "") // remove **bold** title blocks
    .replace(/#{1,6}\s+/g, "") // remove markdown headers
    .trim()
    .split(/\n\n+/)
    .filter((p) => p.trim());

  return (
    <article>
      {/* Section label */}
      <p className="mb-2 text-sm font-semibold uppercase tracking-widest text-accent">
        {isRecap ? "Week in Review" : "Week Ahead"}
      </p>

      {/* Headline */}
      <h2 className="mb-2 text-2xl font-bold text-foreground sm:text-3xl">
        {summary.summary_type_display}
      </h2>

      {/* Meta line */}
      <p className="mb-6 text-sm text-muted-foreground">
        Week {summary.week_number}, {summary.year}
        {summary.votes_included.length > 0 && (
          <> · {summary.votes_included.length} votes</>
        )}
        {summary.bills_included.length > 0 && (
          <> · {summary.bills_included.length} bills</>
        )}
      </p>

      {/* AI disclaimer — top */}
      <div className="mb-6 border-l-2 border-muted-foreground/30 pl-4">
        <AiDisclaimer />
      </div>

      {/* Body paragraphs */}
      <div className="space-y-5">
        {paragraphs.map((paragraph, i) => (
          <p
            key={i}
            className="text-base leading-relaxed text-foreground/85"
          >
            {paragraph.replace(/\*([^*]+)\*/g, "$1").trim()}
          </p>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-8 border-t border-border pt-4">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <time dateTime={summary.created_at}>
            Last updated {formatDateLong(summary.created_at.split("T")[0])}
          </time>
          <Link
            href={routes.calendar.index}
            className="cursor-pointer font-medium text-accent hover:underline"
          >
            View Full Calendar →
          </Link>
        </div>
        {/* AI disclaimer — bottom */}
        <div className="mt-4">
          <AiDisclaimer />
        </div>
      </div>
    </article>
  );
}

function EmptyState() {
  return (
    <div className="py-16 text-center">
      <h2 className="mb-2 text-lg font-medium text-foreground">
        No Summaries Yet
      </h2>
      <p className="text-muted-foreground">
        Weekly summaries are generated automatically. Check back on Saturday for
        the weekly recap and Sunday for the week ahead preview.
      </p>
    </div>
  );
}

export default async function ThisWeekPage() {
  const summaries = await getCurrentWeeklySummaries();

  const recap = summaries.find((s) => s.summary_type === "recap");
  const preview = summaries.find((s) => s.summary_type === "preview");

  const currentWeek = recap?.week_number || preview?.week_number;
  const currentYear = recap?.year || preview?.year;

  return (
    <ChatContextProvider
      context={{
        type: "this-week",
        data: {
          summary: recap?.content?.slice(0, 500) || "",
          week_number: currentWeek,
          year: currentYear,
        },
      }}
    >
      <main className="min-h-screen bg-background">
        {/* Narrow centered column — NYT article style */}
        <div className="mx-auto max-w-2xl px-4 py-8 sm:px-6">
          {/* Page header */}
          <header className="mb-8">
            <p className="mb-1 text-sm uppercase tracking-widest text-muted-foreground">
              OpenCongress
            </p>
            <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
              This Week in Congress
            </h1>
            {currentWeek && currentYear && (
              <p className="mt-2 text-muted-foreground">
                Week {currentWeek}, {currentYear}
              </p>
            )}
          </header>

          <Separator className="mb-8" />

          {/* Articles */}
          {summaries.length === 0 ? (
            <EmptyState />
          ) : (
            <div className="space-y-12">
              {recap && <SummaryArticle summary={recap} />}
              {recap && preview && <Separator />}
              {preview && <SummaryArticle summary={preview} />}
            </div>
          )}

          {/* Bottom nav */}
          <nav className="mt-12 border-t border-border pt-6">
            <div className="flex items-center justify-between text-sm">
              <Link
                href={routes.home}
                className="cursor-pointer font-medium text-foreground hover:text-accent"
              >
                ← Back to Home
              </Link>
              <Link
                href={routes.calendar.index}
                className="cursor-pointer font-medium text-foreground hover:text-accent"
              >
                Full Calendar →
              </Link>
            </div>
          </nav>
        </div>
      </main>
    </ChatContextProvider>
  );
}
