# Generated by Django 5.2.10 on 2026-02-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
