# Generated by Django 5.2.10 on 2026-01-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AISummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("bill", "Bill"),
                            ("vote", "Vote"),
                            ("member", "Member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.CharField(max_length=50)),
                ("summary_text", models.TextField()),
                ("model_used", models.CharField(max_length=50)),
                ("prompt_version", models.CharField(max_length=20)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_summaries",
                "unique_together": {("content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="NewsLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField()),
                ("source", models.CharField(max_length=200)),
                ("published_at", models.DateTimeField()),
                ("bill_id", models.CharField(blank=True, max_length=50)),
                ("vote_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "news_links",
                "indexes": [
                    models.Index(
                        fields=["bill_id"], name="news_links_bill_id_dfd6dd_idx"
                    ),
                    models.Index(
                        fields=["vote_id"], name="news_links_vote_id_ae1336_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrendReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("data", models.JSONField()),
                ("summary_text", models.TextField()),
                ("model_used", models.CharField(max_length=50)),
                ("prompt_version", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trend_reports",
                "indexes": [
                    models.Index(
                        fields=["report_type", "period_start"],
                        name="trend_repor_report__e657c2_idx",
                    )
                ],
            },
        ),
    ]
