# Generated by Django 5.2.10 on 2026-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("week_number", models.IntegerField()),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("recap", "Week in Review"),
                            ("preview", "Week Ahead"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("model_used", models.CharField(max_length=50)),
                ("prompt_version", models.CharField(max_length=20)),
                ("tokens_used", models.IntegerField(default=0)),
                ("votes_included", models.JSONField(default=list)),
                ("bills_included", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "weekly_summaries",
                "indexes": [
                    models.Index(
                        fields=["year", "week_number"],
                        name="weekly_summ_year_b005ee_idx",
                    )
                ],
                "unique_together": {("year", "week_number", "summary_type")},
            },
        ),
    ]
