# Generated by Django 5.2.10 on 2026-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_weeklysummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "summary_type",
                    models.CharField(
                        choices=[("recap", "Daily Recap"), ("preview", "Day Ahead")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("model_used", models.CharField(max_length=50)),
                ("prompt_version", models.CharField(max_length=20)),
                ("tokens_used", models.IntegerField(default=0)),
                ("votes_included", models.JSONField(default=list)),
                ("bills_included", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_summaries",
                "indexes": [
                    models.Index(fields=["date"], name="daily_summa_date_4d8318_idx")
                ],
                "unique_together": {("date", "summary_type")},
            },
        ),
    ]
