# Generated by Django 5.2.10 on 2026-02-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_create_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="log",
            field=models.TextField(blank=True, default=""),
        ),
    ]
