# Generated by Django 5.2.10 on 2026-01-31 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "committee_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "House of Representatives"),
                            ("senate", "Senate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "committees",
                "ordering": ["chamber", "name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "bioguide_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                (
                    "party",
                    models.CharField(
                        choices=[
                            ("D", "Democrat"),
                            ("R", "Republican"),
                            ("I", "Independent"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "House of Representatives"),
                            ("senate", "Senate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("district", models.IntegerField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("office_address", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("contact_url", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=50)),
                ("facebook_id", models.CharField(blank=True, max_length=100)),
                ("youtube_id", models.CharField(blank=True, max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=1)),
                ("seniority_date", models.DateField(blank=True, null=True)),
                ("term_start", models.DateField(blank=True, null=True)),
                ("term_end", models.DateField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True)),
                ("ai_bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "members",
                "indexes": [
                    models.Index(
                        fields=["chamber", "state"], name="members_chamber_7ce53b_idx"
                    ),
                    models.Index(
                        fields=["state", "district"], name="members_state_f1bcba_idx"
                    ),
                    models.Index(fields=["party"], name="members_party_794bb1_idx"),
                    models.Index(
                        fields=["last_name"], name="members_last_na_c32184_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="members_is_acti_246c8e_idx"
                    ),
                    models.Index(
                        fields=["chamber", "party", "state"], name="member_filter_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "bill_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("hr", "House Bill"),
                            ("s", "Senate Bill"),
                            ("hjres", "House Joint Resolution"),
                            ("sjres", "Senate Joint Resolution"),
                            ("hconres", "House Concurrent Resolution"),
                            ("sconres", "Senate Concurrent Resolution"),
                            ("hres", "House Resolution"),
                            ("sres", "Senate Resolution"),
                        ],
                        max_length=10,
                    ),
                ),
                ("number", models.IntegerField()),
                ("congress", models.IntegerField()),
                ("title", models.TextField()),
                ("short_title", models.CharField(blank=True, max_length=500)),
                ("display_number", models.CharField(max_length=50)),
                ("summary_text", models.TextField(blank=True)),
                ("summary_html", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("introduced_date", models.DateField(blank=True, null=True)),
                ("latest_action_date", models.DateField(blank=True, null=True)),
                ("latest_action_text", models.TextField(blank=True)),
                ("congress_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_bills",
                        to="congress.member",
                    ),
                ),
            ],
            options={
                "db_table": "bills",
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "seat_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "House of Representatives"),
                            ("senate", "Senate"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("democrat", "Democrat"),
                            ("republican", "Republican"),
                            ("independent", "Independent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("row", models.IntegerField()),
                ("position", models.IntegerField()),
                ("svg_x", models.FloatField()),
                ("svg_y", models.FloatField()),
                (
                    "member",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seat",
                        to="congress.member",
                    ),
                ),
            ],
            options={
                "db_table": "seats",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "vote_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "House of Representatives"),
                            ("senate", "Senate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("congress", models.IntegerField()),
                ("session", models.IntegerField()),
                ("roll_call", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("question", models.CharField(max_length=200)),
                ("question_text", models.TextField(blank=True)),
                ("description", models.TextField()),
                ("vote_type", models.CharField(blank=True, max_length=50)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("agreed", "Agreed to"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_yea", models.IntegerField(default=0)),
                ("total_nay", models.IntegerField(default=0)),
                ("total_present", models.IntegerField(default=0)),
                ("total_not_voting", models.IntegerField(default=0)),
                ("dem_yea", models.IntegerField(default=0)),
                ("dem_nay", models.IntegerField(default=0)),
                ("dem_present", models.IntegerField(default=0)),
                ("dem_not_voting", models.IntegerField(default=0)),
                ("rep_yea", models.IntegerField(default=0)),
                ("rep_nay", models.IntegerField(default=0)),
                ("rep_present", models.IntegerField(default=0)),
                ("rep_not_voting", models.IntegerField(default=0)),
                ("ind_yea", models.IntegerField(default=0)),
                ("ind_nay", models.IntegerField(default=0)),
                ("ind_present", models.IntegerField(default=0)),
                ("ind_not_voting", models.IntegerField(default=0)),
                ("is_bipartisan", models.BooleanField(default=False)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="votes",
                        to="congress.bill",
                    ),
                ),
            ],
            options={
                "db_table": "votes",
            },
        ),
        migrations.CreateModel(
            name="MemberVote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("yea", "Yea"),
                            ("nay", "Nay"),
                            ("present", "Present"),
                            ("not_voting", "Not Voting"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="congress.member",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_votes",
                        to="congress.vote",
                    ),
                ),
            ],
            options={
                "db_table": "member_votes",
            },
        ),
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chair", "Chair"),
                            ("ranking", "Ranking Member"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="congress.committee",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_assignments",
                        to="congress.member",
                    ),
                ),
            ],
            options={
                "db_table": "committee_members",
                "unique_together": {("committee", "member")},
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["congress", "bill_type"], name="bills_congres_a483b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["introduced_date"], name="bills_introdu_6c7448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["chamber", "date"], name="votes_chamber_5cac0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["congress", "session"], name="votes_congres_0ef479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["-date", "-time"], name="votes_date_030327_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["bill"], name="votes_bill_id_30b4b9_idx"),
        ),
        migrations.AddIndex(
            model_name="membervote",
            index=models.Index(
                fields=["member", "position"], name="member_vote_member__06c8ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membervote",
            index=models.Index(
                fields=["vote", "position"], name="member_vote_vote_id_a5640f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membervote",
            unique_together={("vote", "member")},
        ),
    ]
