# Generated by Django 5.2.10 on 2026-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="ai_summary_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="ai_summary_model",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="bill",
            name="ai_summary_prompt_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="member",
            name="ai_bio_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="ai_bio_model",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="ai_bio_prompt_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
