# Generated by Django 5.2.10 on 2026-02-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congress", "0002_bill_ai_summary_created_at_bill_ai_summary_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="committee_id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
