# Generated by Django 5.2.10 on 2026-02-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("congress", "0004_enable_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="ai_summary_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="ai_summary_model",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vote",
            name="ai_summary_prompt_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
