# Generated by Django 5.2.10 on 2026-02-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("congress", "0005_vote_ai_summary_vote_ai_summary_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="committee",
            name="ai_summary_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="committee",
            name="ai_summary_model",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="committee",
            name="ai_summary_prompt_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="committee",
            name="committee_type",
            field=models.CharField(
                choices=[
                    ("standing", "Standing"),
                    ("select", "Select"),
                    ("joint", "Joint"),
                    ("subcommittee", "Subcommittee"),
                ],
                default="standing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="parent_committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcommittees",
                to="congress.committee",
            ),
        ),
        migrations.CreateModel(
            name="BillCommittee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("referred_date", models.DateField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committees",
                        to="congress.bill",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_bills",
                        to="congress.committee",
                    ),
                ),
            ],
            options={
                "db_table": "bill_committees",
                "unique_together": {("bill", "committee")},
            },
        ),
    ]
