# Generated by Django 5.2.10 on 2026-02-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("congress", "0006_add_committee_fields_and_bill_committee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="chamber",
            field=models.CharField(
                choices=[("house", "House"), ("senate", "Senate"), ("joint", "Joint")],
                max_length=10,
            ),
        ),
    ]
